In [2]:
import nltk

In [66]:
import pandas as pd
messages = pd.read_csv('SMSSpamCollection', sep='\t', names=['label','message'])

In [67]:
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [68]:
import re
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Gauri\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [69]:
from nltk.corpus import stopwords

In [70]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()

In [77]:
corpus=[]

### Stopwords removes the useless words from the sentence which don't have any stronger relevant meaning for predicting the essence of the sentence if it is good or bad. Such commonly occuring words used mostly for grammaratical purpose can be removed using stopwords object created from nltk library

### Using Stemming method to reduce the words and Bag of words CountVectorizer method to vectorize the text into numerical vectors
#### Bag of words creates a vector for each word giving counts of each word in every sentence or training example represented as row

In [78]:
for i in range(0,len(messages)):
    review= re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review= review.lower()
    review= review.split()
    review= [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    
    

In [79]:
corpus[0:5]

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though']

In [80]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_features=5000)
X= cv.fit_transform(corpus).toarray()

In [81]:
y = pd.get_dummies(messages['label'], drop_first=True)

In [82]:
y

spam
0        0
1        0
2        1
3        0
4        0
...    ...
5567     1
5568     0
5569     0
5570     0
5571     0

[5572 rows x 1 columns]

In [83]:
import numpy as np
y = y.iloc[:].values

In [84]:
y[:10]

array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1]], dtype=uint8)

In [85]:
X[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [86]:
X.shape # 5000 features or stemmed words in entire document

(5572, 5000)

In [87]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [88]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model= MultinomialNB().fit(X_train, y_train)

C:\Users\Gauri\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [89]:
ypred = spam_detect_model.predict(X_test)

In [90]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_m = confusion_matrix(ypred, y_test)
confusion_m

array([[946,   8],
       [  9, 152]], dtype=int64)

In [93]:
accuracy = accuracy_score(ypred, y_test)
accuracy

0.9847533632286996

### Using Lemmatization technique for preprocessing of words to get more meaningful words with TFIdf for vectorization of text input into numerical vectors

#### TFIdf gives extra importance or weightage to the uncommon words in every sentence or training example as they can be strong predictors of whether a word was good or bad.

#### Bag of words on the other hand gives equal weightage to all the words.

In [94]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Gauri\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [95]:
from nltk.stem import WordNetLemmatizer

In [96]:
wordnet= WordNetLemmatizer()

In [97]:
corpus1=[]
for i in range(0,len(messages)):
    review= re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review= review.lower()
    review= review.split()
    review= [wordnet.lemmatize(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus1.append(review)

In [98]:
corpus1[:10]

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free']

In [59]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv= TfidfVectorizer(max_features=5000)
X= cv.fit_transform(corpus1).toarray()

In [60]:
X[:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [62]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model= MultinomialNB().fit(X_train, y_train)

C:\Users\Gauri\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [63]:
ypred = spam_detect_model.predict(X_test)

In [64]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_m = confusion_matrix(ypred, y_test)
confusion_m

array([[955,  26],
       [  0, 134]], dtype=int64)

In [65]:
accuracy = accuracy_score(ypred, y_test)
accuracy

0.9766816143497757